import type { Metadata } from "next";
import { Geist, Geist_Mono, Pridi } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const pridiFont = Pridi({
  weight: ["200", "300", "400", "500", "600", "700"],
  variable: "--font-pridi",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Boximity MSP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pridiFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
