---
# Ansible playbook for setting up the QA environment for dotca
# This replaces the Terraform bootstrap process

- name: Setup QA environment for dotca
  hosts: digitalocean
  become: true
  vars:
    project_name: dotca-nextjs
    git_repo_url: "{{ lookup('env', 'GIT_REPO_URL') }}"
    git_branch: qa
    app_dir: /app
    public_ip: "{{ ansible_host }}"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes

    - name: Install Docker prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - git
          - python3-pip
        state: present
        update_cache: yes

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes

    - name: Install Docker Engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'

    - name: Clone the repository
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ app_dir }}/repo"
        version: "{{ git_branch }}"
        force: yes

    - name: Create deploy script
      copy:
        dest: "{{ app_dir }}/deploy.sh"
        mode: '0755'
        content: |
          #!/bin/bash
          set -e

          echo "Starting deployment process for dotca QA environment..."
          cd {{ app_dir }}/repo
          echo "Changed to repository directory: {{ app_dir }}/repo"

          # Get the public IP address
          PUBLIC_IP={{ public_ip }}
          echo "Using public IP address: $PUBLIC_IP"

          # Pull latest changes
          echo "Pulling latest changes from {{ git_branch }} branch..."
          git pull origin {{ git_branch }}
          echo "Repository updated successfully."

          # Build the Docker image locally
          echo "Building Docker image with production configuration..."
          docker build \
            --build-arg NODE_ENV=production \
            --build-arg NEXT_PUBLIC_API_URL=http://$PUBLIC_IP/api \
            --build-arg NEXT_PUBLIC_ENVIRONMENT=qa \
            -t dotca_qa:latest .
          echo "Docker image built successfully: dotca_qa:latest"

          # Stop and remove any existing container
          echo "Stopping any existing dotca_qa container..."
          docker stop dotca_qa || echo "No container to stop."
          echo "Removing any existing dotca_qa container..."
          docker rm dotca_qa || echo "No container to remove."

          # Run the new container
          echo "Starting new dotca_qa container..."
          docker run -d \
            --name dotca_qa \
            -p 80:3000 \
            -e NODE_ENV=production \
            -e NEXT_PUBLIC_API_URL=http://$PUBLIC_IP/api \
            -e NEXT_PUBLIC_ENVIRONMENT=qa \
            dotca_qa:latest
          echo "Deployment completed successfully! Application is now available at http://$PUBLIC_IP"

    - name: Run deploy script
      command: "{{ app_dir }}/deploy.sh"

    - name: Setup firewall (UFW)
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - '22'
        - '80'
        - '443'

    - name: Enable UFW
      ufw:
        state: enabled
        policy: deny