---
# Ansible playbook for running Terraform to provision infrastructure

- name: Run Terraform to provision QA infrastructure
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    terraform_dir: "{{ playbook_dir }}/../terraform"
    output_file: "{{ playbook_dir }}/terraform_output.json"
  
  tasks:
    - name: Ensure terraform directory exists
      file:
        path: "{{ terraform_dir }}"
        state: directory
        
    - name: Initialize Terraform
      command:
        cmd: terraform init
        chdir: "{{ terraform_dir }}"
      
    - name: Apply Terraform configuration
      command:
        cmd: terraform apply -auto-approve
        chdir: "{{ terraform_dir }}"
      environment:
        TF_VAR_do_token: "{{ lookup('env', 'DO_TOKEN') }}"
        TF_VAR_ssh_key_fingerprint: "{{ lookup('env', 'SSH_KEY_FINGERPRINT') }}"
        TF_VAR_git_repo_url: "{{ lookup('env', 'GIT_REPO_URL') }}"
        TF_VAR_git_branch: "qa"
      register: terraform_apply
      
    - name: Output Terraform apply result
      debug:
        var: terraform_apply.stdout_lines
        
    - name: Extract Terraform outputs
      command:
        cmd: terraform output -json
        chdir: "{{ terraform_dir }}"
      register: terraform_output
      
    - name: Save Terraform outputs to file
      copy:
        content: "{{ terraform_output.stdout }}"
        dest: "{{ output_file }}"
        
    - name: Load IP address from Terraform outputs
      set_fact:
        droplet_ip: "{{ (terraform_output.stdout | from_json).qa_droplet_ip.value }}"
        
    - name: Wait for SSH to be available
      wait_for:
        host: "{{ droplet_ip }}"
        port: 22
        delay: 10
        timeout: 300
        
    - name: Update inventory with new droplet
      add_host:
        name: "qa_droplet"
        groups: digitalocean
        ansible_host: "{{ droplet_ip }}"
        ansible_user: root
        
    - name: Trigger Ansible configuration
      command:
        cmd: ansible-playbook {{ playbook_dir }}/qa-config.yml
      environment:
        ANSIBLE_HOST_KEY_CHECKING: "False"