name: QA Deploy (Legacy)

on:
  # This workflow is kept for reference but is now disabled
  # Use qa-terraform.yml and qa-ansible.yml instead
  workflow_dispatch:

jobs:
  deploy-qa-legacy:
    name: Legacy QA Deployment (Disabled)
    runs-on: ubuntu-latest
    steps:
      - name: Notice
        run: |
          echo "⚠️ This workflow is deprecated. Please use the separate Terraform and Ansible workflows instead."
          echo "See qa-terraform.yml and qa-ansible.yml for the new separated workflows."